export class AboutContent {
    /*
     * TODO: Replace Lorem Ipsum with About Content 
     */

    static readonly aboutDigitalTechnologiesRadarContent = "Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Sapien pellentesque habitant morbi tristique senectus et netus et malesuada. Ornare arcu dui vivamus arcu felis. Eget sit amet tellus cras adipiscing enim eu turpis egestas. Nulla at volutpat diam ut venenatis tellus in. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed. Feugiat in fermentum posuere urna nec. Orci a scelerisque purus semper eget duis at. Vitae congue eu consequat ac felis donec et. Nulla facilisi cras fermentum odio. Mauris vitae ultricies leo integer malesuada nunc vel. Eu scelerisque felis imperdiet proin fermentum leo.";
    static readonly aboutDigitalResilienceTeamContent = "Integer quis auctor elit sed vulputate mi sit amet. Cras pulvinar mattis nunc sed blandit libero volutpat. Pulvinar etiam non quam lacus. Mauris ultrices eros in cursus turpis massa tincidunt. Sit amet aliquam id diam maecenas ultricies mi eget mauris. Dignissim suspendisse in est ante in. Pretium vulputate sapien nec sagittis. In hac habitasse platea dictumst vestibulum rhoncus. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Leo in vitae turpis massa sed. Fermentum iaculis eu non diam phasellus vestibulum lorem.";
    static readonly aboutSDGAiLabContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Velit euismod in pellentesque massa placerat duis ultricies. Bibendum arcu vitae elementum curabitur vitae nunc. Aenean vel elit scelerisque mauris. Etiam erat velit scelerisque in dictum non consectetur a. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Dui id ornare arcu odio. Pulvinar mattis nunc sed blandit libero volutpat sed cras. Eu sem integer vitae justo eget magna fermentum iaculis. Arcu non odio euismod lacinia at.";
    
}