name: CI Development

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ''16.20.1''

      - run: git config --global url."https://${{ secrets.PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: install
        run: |
          yarn install

      - name: build
        run: |
          yarn build

      - name: test
        run: |
          yarn test
        env:
          NODE_ENV: development
          CI: true
